/** biome-ignore-all lint/suspicious/noConsole: dev plugin */

import fs from "node:fs";
import path from "node:path";
import { camelCase, mapValues, pascalCase } from "es-toolkit";

type MessagesObject = { [K: string]: MessagesObject | string };

export const langDir = path.resolve(import.meta.dirname, "../../../lang");

export const i18nDir = path.resolve(import.meta.dirname, "../../../src/i18n");

const messagesFileRegExp =
	/lang\/([a-z]{2}-[A-Z]{2})\/(editor|player|shared)\/(.*)\.json$/;

export default async function generateMessagesFiles() {
	console.log("Generating i18n messages files... ");

	const files = await fs.promises.readdir(langDir, {
		recursive: true,
	});

	const messagesPaths: Record<string, Record<string, string[]>> = {};

	files.forEach((file) => {
		const matches = messagesFileRegExp.exec(path.resolve(langDir, file));
		if (matches?.[1] && matches[2] && matches[3]) {
			const locale = matches[1];
			const scope = matches[2];
			const path = matches[3];

			messagesPaths[locale] = {
				...messagesPaths[locale],
				[scope]: [...(messagesPaths[locale]?.[scope] ?? []), path],
			};
		}
	});

	let scopesData: Record<
		string,
		{
			paths: Record<string, string>;
			messages: Record<string, MessagesObject>;
		}
	> = {};

	Object.entries(messagesPaths).forEach(([locale, scopes]) => {
		Object.entries(scopes).forEach(([scope, paths]) => {
			const messages = paths.reduce<MessagesObject>((mergedMessages, path) => {
				path.split("/").reduce((current, segment, index, segments) => {
					if (index === segments.length - 1) {
						current[segment] =
							`${camelCase(locale)}${pascalCase(segments.join("/"))}`;
					} else {
						current[segment] = current[segment] ?? {};
					}

					return current[segment] as MessagesObject;
				}, mergedMessages);

				return mergedMessages;
			}, {});

			scopesData = {
				...scopesData,
				[scope]: {
					paths: {
						...scopesData[scope]?.paths,
						...Object.fromEntries(
							paths.map((path) => [
								`${camelCase(locale)}${pascalCase(path)}`,
								`${locale}/${scope}/${path}`,
							]),
						),
					},
					messages: {
						...scopesData[scope]?.messages,
						[locale]: messages,
					},
				},
			};
		});
	});

	await Promise.all(
		Object.entries(scopesData).map(async ([scope, { paths, messages }]) => {
			const file = path.resolve(i18nDir, "messages", `${scope}.ts`);
			const fileImports = Object.entries(paths)
				.flatMap(
					([name, path]) => `import ${name} from "../../../lang/${path}.json";`,
				)
				.sort()
				.join("\n");
			const fileExport = JSON.stringify(
				mapValues(messages, (m) => ({ [scope]: m })),
				null,
				"\t",
			)
				.replaceAll(/(["}])\n/g, "$1,\n")
				.replaceAll(/"([a-zA-Z]+)"/g, "$1");

			const content = `
// DO NOT EDIT THIS FILE (generated by a vite plugin: i18nMessagesPlugin).
${fileImports}

export default ${fileExport};
`.trimStart();

			await fs.promises.writeFile(file, content, "utf-8");
		}),
	);
}
