// DO NOT EDIT THIS FILE (generated by a vite plugin: i18nMessagesPlugin).
import enUsApp from "../../../lang/en-US/editor/app.json";
import enUsAppBar from "../../../lang/en-US/editor/appBar.json";
import enUsDrawerTabWindowCaseTabWindow from "../../../lang/en-US/editor/drawerTabWindow/caseTabWindow.json";
import enUsDrawerTabWindowLayoutTabWindow from "../../../lang/en-US/editor/drawerTabWindow/layoutTabWindow.json";
import enUsEditionToolbar from "../../../lang/en-US/editor/editionToolbar.json";
import enUsGridActions from "../../../lang/en-US/editor/grid/actions.json";
import enUsGridForms from "../../../lang/en-US/editor/grid/forms.json";
import frFrApp from "../../../lang/fr-FR/editor/app.json";
import frFrAppBar from "../../../lang/fr-FR/editor/appBar.json";
import frFrDrawerTabWindowCaseTabWindow from "../../../lang/fr-FR/editor/drawerTabWindow/caseTabWindow.json";
import frFrDrawerTabWindowLayoutTabWindow from "../../../lang/fr-FR/editor/drawerTabWindow/layoutTabWindow.json";
import frFrEditionToolbar from "../../../lang/fr-FR/editor/editionToolbar.json";
import frFrGridActions from "../../../lang/fr-FR/editor/grid/actions.json";
import frFrGridForms from "../../../lang/fr-FR/editor/grid/forms.json";

export default {
	"fr-FR": {
		editor: {
			app: frFrApp,
			appBar: frFrAppBar,
			editionToolbar: frFrEditionToolbar,
			grid: {
				actions: frFrGridActions,
				forms: frFrGridForms,
			},
			drawerTabWindow: {
				caseTabWindow: frFrDrawerTabWindowCaseTabWindow,
				layoutTabWindow: frFrDrawerTabWindowLayoutTabWindow,
			},
		},
	},
	"en-US": {
		editor: {
			app: enUsApp,
			appBar: enUsAppBar,
			editionToolbar: enUsEditionToolbar,
			grid: {
				actions: enUsGridActions,
				forms: enUsGridForms,
			},
			drawerTabWindow: {
				caseTabWindow: enUsDrawerTabWindowCaseTabWindow,
				layoutTabWindow: enUsDrawerTabWindowLayoutTabWindow,
			},
		},
	},
};
