// DO NOT EDIT THIS FILE (generated by a vite plugin: i18nMessagesPlugin).
import enUsApp from "../../../lang/en-US/player/app.json";
import frFrApp from "../../../lang/fr-FR/player/app.json";

export default {
	"fr-FR": {
		player: {
			app: frFrApp,
		},
	},
	"en-US": {
		player: {
			app: enUsApp,
		},
	},
};
