// DO NOT EDIT THIS FILE (generated by a vite plugin: i18nMessagesPlugin).
import enUsActions from "../../../lang/en-US/shared/actions.json";
import enUsCommon from "../../../lang/en-US/shared/common.json";
import enUsConfig from "../../../lang/en-US/shared/config.json";
import enUsValidationRules from "../../../lang/en-US/shared/validation/rules.json";
import frFrActions from "../../../lang/fr-FR/shared/actions.json";
import frFrCommon from "../../../lang/fr-FR/shared/common.json";
import frFrConfig from "../../../lang/fr-FR/shared/config.json";
import frFrValidationRules from "../../../lang/fr-FR/shared/validation/rules.json";

export default {
	"fr-FR": {
		shared: {
			actions: frFrActions,
			common: frFrCommon,
			config: frFrConfig,
			validation: {
				rules: frFrValidationRules,
			},
		},
	},
	"en-US": {
		shared: {
			actions: enUsActions,
			common: enUsCommon,
			config: enUsConfig,
			validation: {
				rules: enUsValidationRules,
			},
		},
	},
};
