// DO NOT EDIT THIS FILE (generated by a vite plugin: i18nMessagesPlugin).
import enUsApp from "../../../lang/en-US/editor/app.json";
import enUsEditionToolbar from "../../../lang/en-US/editor/editionToolbar.json";
import enUsGridActions from "../../../lang/en-US/editor/grid/actions.json";
import enUsGridForms from "../../../lang/en-US/editor/grid/forms.json";
import frFrApp from "../../../lang/fr-FR/editor/app.json";
import frFrEditionToolbar from "../../../lang/fr-FR/editor/editionToolbar.json";
import frFrGridActions from "../../../lang/fr-FR/editor/grid/actions.json";
import frFrGridForms from "../../../lang/fr-FR/editor/grid/forms.json";

export default {
	"fr-FR": {
		editor: {
			app: frFrApp,
			editionToolbar: frFrEditionToolbar,
			grid: {
				actions: frFrGridActions,
				forms: frFrGridForms,
			},
		},
	},
	"en-US": {
		editor: {
			app: enUsApp,
			editionToolbar: enUsEditionToolbar,
			grid: {
				actions: enUsGridActions,
				forms: enUsGridForms,
			},
		},
	},
};
