name: 'build_windows'

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Application to build'
        required: true
        default: 'editor'
        type: choice
        options:
          - editor
          - player

      build:
        description: 'Build type'
        required: true
        default: 'windows - online'
        type: choice
        options:
          - windows - online
          - windows - offline

  workflow_call:
    inputs:
      target:
        description: 'Application to build'
        required: true
        type: string
      build:
        description: 'Build type'
        required: true
        type: string

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7

      - name: Enable Corepack
        shell: bash
        run: corepack enable

      - name: Install pnpm
        shell: bash
        run: corepack prepare pnpm@latest --activate

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: apps/lifecompanion/src-tauri/${{ inputs.target }} -> target

      - name: install frontend dependencies
        run: pnpm install

      # --------------------
      # Build
      # --------------------

      - uses: tauri-apps/tauri-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: apps/lifecompanion/src-tauri/${{ inputs.target }}
          tagName: ${{ inputs.target }}-v__VERSION__
          releaseName: '${{ inputs.target }} v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: false
          prerelease: false
          args: ''