name: 'build_windows'

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Application to build'
        required: true
        default: 'editor'
        type: choice
        options:
          - editor
          - player

      build:
        description: 'Build type'
        required: true
        default: 'windows - online'
        type: choice
        options:
          - windows - online
          - windows - offline

  workflow_call:
    inputs:
      target:
        description: 'Application to build'
        required: true
        type: string
      build:
        description: 'Build type'
        required: true
        type: string

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup build environment
        uses: ./.github/actions/setup_build
        with:
          target: ${{ inputs.target }}
          tauri-signing-private-key: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          tauri-signing-private-key-password: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

      # --------------------
      # Build
      # --------------------

      - uses: tauri-apps/tauri-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: apps/lifecompanion/src-tauri/${{ inputs.app }}
          tagName: ${{ inputs.app }}-v__VERSION__
          releaseName: '${{ inputs.app }} v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: false
          prerelease: false
          args: ''