name: 'build'

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Application to build'
        required: true
        default: 'editor'
        type: choice
        options:
          - editor
          - player
          - sharded

      build:
        description: 'Build type'
        required: true
        default: 'windows - online'
        type: choice
        options:
          - windows - online
          - windows - offline
          - linux
          - android - debug apk
          - android - release aab

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set Docker UID/GID
        run: |
          echo "UID=$(id -u)" >> "$GITHUB_ENV"
          echo "GID=$(id -g)" >> "$GITHUB_ENV"

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf xdg-utils

      # --------------------
      # Build
      # --------------------

      - name: Build Windows Online
        if: inputs.build == 'windows - online'
        run: make build-windows target=${{ inputs.target }} variant=online bundle=true release=true

      - name: Build Windows Offline
        if: inputs.build == 'windows - offline'
        run: make build-windows target=${{ inputs.target }} variant=offline bundle=true release=true

      - name: Build Linux
        if: inputs.build == 'linux'
        run: make build-linux target=${{ inputs.target }} bundle=true release=true

      - name: Build Android AAB
        if: inputs.build == 'android - aab'
        run: make build-android target=${{ inputs.target }} android_format=aab release=true

      - name: Build Android APK
        if: inputs.build == 'android - debug apk'
        run: make build-android target=${{ inputs.target }} android_format=apk

      # --------------------
      # Store artifact
      # --------------------

      - name: Store Windows Online as artifact
        if: inputs.build == 'windows - online'
        uses: actions/upload-artifact@v4
        with:
          name: lifecompanion-${{ inputs.target }}-windows-online
          path: target/lifecompanion-${{ inputs.target }}/x86_64-pc-windows-msvc/release/bundle/nsis/*-setup.exe
          if-no-files-found: error

      - name: Store Windows Offline as artifact
        if: inputs.build == 'windows - offline'
        uses: actions/upload-artifact@v4
        with:
          name: lifecompanion-${{ inputs.target }}-windows-offline
          path: target/lifecompanion-${{ inputs.target }}/x86_64-pc-windows-msvc/release/bundle/nsis/*-setup.exe
          if-no-files-found: error

      - name: Store linux as artifact
        if: inputs.build == 'linux'
        uses: actions/upload-artifact@v4
        with:
          name: lifecompanion-${{ inputs.target }}-linux
          path: |
            target/lifecompanion-${{ inputs.target }}/release/bundle/deb/*.deb
            target/lifecompanion-${{ inputs.target }}/release/bundle/rpm/*.rpm
            target/lifecompanion-${{ inputs.target }}/release/bundle/appimage/*.AppImage
          if-no-files-found: error

      - name: Store android APK as artifact
        if: inputs.build == 'android - debug apk'
        uses: actions/upload-artifact@v4
        with:
          name: lifecompanion-${{ inputs.target }}-android-apk
          path: apps/lifecompanion/src-tauri/${{ inputs.target }}/gen/android/app/build/outputs/apk/universal/debug/*.apk
          if-no-files-found: error

      - name: Store android AAB as artifact
        if: inputs.build == 'android - aab'
        uses: actions/upload-artifact@v4
        with:
          name: lifecompanion-${{ inputs.target }}-android-aab
          path: apps/lifecompanion/src-tauri/${{ inputs.target }}/gen/android/app/build/outputs/bundle/universalRelease/*.aab
          if-no-files-found: error