name: 'build_windows'

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set Docker UID/GID
        run: |
          echo "UID=$(id -u)" >> "$GITHUB_ENV"
          echo "GID=$(id -g)" >> "$GITHUB_ENV"

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf xdg-utils

      - name: Build Windows
        run: make build-windows target=editor bundle=true release=true

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: lifecompanion-editor-windows
          path: |
            target/lifecompanion-editor/x86_64-pc-windows-msvc/debug/lifecompanion-editor.exe
          if-no-files-found: error