name: 'publish'

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    outputs:
      release_id: ${{ steps.create-release.outputs.result }}

    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: version
        run: |
          echo "VERSION=$(node -p "require('./apps/lifecompanion/package.json').version")" >> $GITHUB_ENV

      - name: Create GitHub release
        id: create-release
        uses: actions/github-script@v7
        with:
          script: |
            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: context.ref.replace('refs/tags/', ''),
              name: `Life Companion ${process.env.VERSION}`,
              body: 'Download the latest version.',
              draft: true,
              prerelease: false
            })

            return release.data.id

  build-tauri:
    needs: [create-release]

    permissions:
      contents: write

    strategy:
      fail-fast: false

      matrix:
        include:
          - platform: 'windows-latest'
            args: '--config tauri.windows-online.conf.json'
          - platform: 'windows-latest'
            args: '--config tauri.windows-offline.conf.json'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'ubuntu-22.04'
            args: '--aab'
            mobile: 'android'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v7


      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' && matrix.mobile != 'android'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev

      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.x.x

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 26.x.0
          cache: pnpm

      - name: install frontend dependencies
        run: pnpm install

      - name: install Rust stable
        if: matrix.mobile == 'android'
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android

      - name: Set up JDK
        if: matrix.mobile == 'android'
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        if: matrix.mobile == 'android'
        uses: android-actions/setup-android@v3

      - name: Setup Android NDK
        if: matrix.mobile == 'android'
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r29
          link-to-sdk: true

      - name: Setup Rust target directory
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          echo "CARGO_TARGET_DIR=${{ github.workspace }}/apps/lifecompanion/src-tauri/editor" >> $GITHUB_ENV

      - name: init mobile project
        if: matrix.mobile == 'android'
        run: |
          cd ./apps/lifecompanion/src-tauri/editor
          pnpm dlx @tauri-apps/cli android init

      - name: Setup Android signing
        if: matrix.mobile == 'android'
        run: |
          cd apps/lifecompanion/src-tauri/editor/gen/android
          echo "keyAlias=${{ secrets.TAURI_ANDROID_KEY_ALIAS }}" > keystore.properties
          echo "password=${{ secrets.TAURI_ANDROID_KEY_PASSWORD }}" >> keystore.properties
          base64 -d <<< "${{ secrets.TAURI_ANDROID_KEY_BASE64 }}" > $RUNNER_TEMP/keystore.jks
          echo "storeFile=$RUNNER_TEMP/keystore.jks" >> keystore.properties

      - name: Extract publication information
        if: matrix.mobile == 'android'
        id: publication
        run: |
          echo "APP_VERSION=${GITHUB_REF}" >> $GITHUB_OUTPUT
          echo "APP_TRACK=$(echo ${GITHUB_REF} | grep -oP "(?<=-).*(?=\.)" || echo "production")" >> $GITHUB_OUTPUT

      - name: Publication information
        if: matrix.mobile == 'android'
        run: |
          echo "Version ${{ steps.publication.outputs.APP_VERSION }}."
          echo "Publishing on track ${{ steps.publication.outputs.APP_TRACK }}."

      # --------------------
      # Build
      # --------------------
      - uses: tauri-apps/tauri-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          projectPath: apps/lifecompanion/src-tauri/editor

          releaseId: ${{ needs.create-release.outputs.release_id }}
          uploadUpdaterSignatures: true
          uploadUpdaterJson: true

          args: "${{ matrix.args }}"
          mobile: ${{ matrix.mobile }}

      - name: Deploy to Google Play
        if: matrix.mobile == 'android' && github.ref_type == 'tag' && false == true
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          packageName: org.lifecompanion2.editor
          releaseFiles: apps/lifecompanion/src-tauri/editor/gen/android/app/build/outputs/bundle/universalRelease/*.aab
          track: ${{ env.TRACK }}
        env:
          TRACK: ${{ steps.publication.outputs.APP_TRACK }}

  publish-release:
    needs: [create-release, build-tauri]

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Publish release
        uses: actions/github-script@v7
        env:
          RELEASE_ID: ${{ needs.create-release.outputs.release_id }}
        with:
          script: |
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.RELEASE_ID,
              draft: false,
              prerelease: false
            })

