name: 'publish_android'

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Application to build'
        required: true
        default: 'editor'
        type: choice
        options:
          - editor
          - player

  workflow_call:
    inputs:
      target:
        description: 'Application to build'
        required: true
        type: string

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup build environment
        uses: ./.github/actions/setup_build
        with:
          tauri-signing-private-key: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          tauri-signing-private-key-password: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

      - name: Setup Android signing
        run: |
          cd src-tauri/${{ inputs.target }}/gen/android
          echo "keyAlias=${{ secrets.TAURI_ANDROID_KEY_ALIAS }}" > keystore.properties
          echo "password=${{ secrets.TAURI_ANDROID_KEY_PASSWORD }}" >> keystore.properties
          base64 -d <<< "${{ secrets.TAURI_ANDROID_KEY_BASE64 }}" > $RUNNER_TEMP/keystore.jks
          echo "storeFile=$RUNNER_TEMP/keystore.jks" >> keystore.properties

      # --------------------
      # Build
      # --------------------

      - name: Build Android
        uses: ./.github/actions/build_android
        with:
          target: ${{ inputs.target }}
          build: 'aab'

      # --------------------
      # Deploy to Google Play
      # --------------------

      - name: Deploy to Google Play
        if: github.ref_type == 'tag'
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          packageName: org.lifecompanion2.${{ inputs.target }}
          releaseFiles: apps/lifecompanion/src-tauri/${{ inputs.target }}/gen/android/app/build/outputs/bundle/universalRelease/*.aab
          track: ${{ env.TRACK }}
        env:
          TRACK: ${{ steps.publication.outputs.APP_TRACK }}
